apiVersion: apps/v1
kind: Deployment
metadata:
  name: pikubeytes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pikubeytes
  template:
    metadata:
      labels:
        app: pikubeytes
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}  # Resets logs when pod restarts
      containers:
        - name: pikubeytes
          image: picobytes:api  # Change to your actual image name
          volumeMounts:
            - name: log-volume
              mountPath: /app/run_logs  # Matches Python script's log directory
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
