apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:

    metadata:
      labels:
        app: worker
    spec:
      volumes:
        - name: log-volume
          emptyDir: { }
      containers:
        - name: worker
          image: worker:latest
          volumeMounts:
            - name: log-volume
              mountPath: /app/run_logs
          imagePullPolicy: IfNotPresent

        - name: fluent-bit
          image: fluent/fluent-bit:latest
          args:
            - "-i"
            - "tail"
            - "-p"
            - "path=/app/run_logs/*.log"
            - "-o"
            - "stdout"
          volumeMounts:
            - name: log-volume
              mountPath: /app/run_logs